---
- name: Use apache_webserver role
  hosts: node2
  become: true
  pre_tasks:
    - name: Output info before any role execution
      ansible.builtin.debug:
        msg: "Beginning web server configuration."
  post_tasks:
    - name: Output info after all roles are executed
      ansible.builtin.debug:
        msg: "Web server has been configured."
  roles:
    - apache_webserver
