# MkDocs configuration file
site_name: Ansible Workshop
copyright: Copyright &copy; Tim Gr√ºtzmacher 2025
extra:
  social:
    - icon: simple/githubactions
      link: https://github.com/TimGrt/Ansible-Workshop-Exercises/actions
      name: CI/CD Pipelines
    - icon: fontawesome/brands/docker
      link: https://github.com/TimGrt/Ansible-Workshop-Exercises/blob/main/Containerfile
      name: Container Definition
extra_css:
  - assets/stylesheets/tables.css
extra_javascript:
  - assets/javascripts/extra/refresh-on-toggle-dark-light.js
  - assets/javascripts/extra/tablesort.min.js
  - assets/javascripts/extra/tablesort.js
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path:
        - .
        - docs/ansible-core/snippets
        - docs/automation-platform/snippets
        - docs/projects/cloud-automation/snippets
        - docs/projects/linux-automation/snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
plugins:
  - search:
      lang: en
      separator: '[\s]'
  - autolinks:
  - git-revision-date-localized:
    # This plugin needs a Git executable and the .git folder
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
      fallback_to_build_date: true
      locale: en
  - exporter:
    # This plugin requires playwright! For testing, deactivate if necessary
      buttons:
        - title: View as PDF
          icon: material-file-pdf-box
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes:
            target: _blank
            href: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.href
      formats:
        pdf:
          covers:
            back: docs/assets/pdf/back-cover.html.j2
          enabled: !ENV [MKDOCS_EXPORTER_PDF_ENABLED, true]
          explicit: true
          concurrency: 16
          stylesheets:
            - docs/assets/stylesheets/pdf.scss
theme:
  name: material
  # Uncomment to announce the current workshop URL
  custom_dir: docs/assets/overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
      example: octicons/terminal-24
  logo: assets/images/ansible-logo-black.png
  language: en
  favicon: assets/images/ansible-logo-black.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/TimGrt/Ansible-Workshop-Exercises
repo_name: timgrt/ansible-workshop-exercises
watch:
  - includes
# Navigation definition
nav:
  - "Workshop Overview":
    - index.md
    - demo-environment/red-hat-demo-environment.md
    - demo-environment/local-demo-environment.md
    - demo-environment/editor-alternatives.md
  - "Ansible Basics":
    - ansible-basics-overview.md
    - "1 - Check prerequisites": ansible-core/ansible-core-intro.md
    - "2 - Ansible Basics": ansible-core/ansible-core-basics.md
    - "3 - Playbooks": ansible-core/ansible-core-playbook.md
    - "4 - Variables": ansible-core/ansible-core-variables.md
    - "5 - Conditionals": ansible-core/ansible-core-conditionals.md
    - "6 - Loops": ansible-core/ansible-core-loops.md
    - "7 - Handlers": ansible-core/ansible-core-handlers.md
    - "8 - Templates": ansible-core/ansible-core-templates.md
    - "9 - Roles": ansible-core/ansible-core-roles.md
    - ansible-core/ansible-core-supplemental.md
  - "Automation Platform":
    - automation-platform-overview.md
    - "1 - AAP Introduction": automation-platform/automation-platform-intro.md
    - "2 - Inventory & Ad-hoc commands": automation-platform/automation-platform-inventory.md
    - "3 - Projects & Job Templates": automation-platform/automation-platform-projects.md
    - "4 - Surveys": automation-platform/automation-platform-surveys.md
    - "5 - Role-based access control": automation-platform/automation-platform-rbac.md
    - "6 - Workflows": automation-platform/automation-platform-workflows.md
    - "7 - AAP Wrap up": automation-platform/automation-platform-wrapup.md
  - "Projects":
    - projects/projects-overview.md
    - "Project - Linux automation": projects/linux-automation/grafana-project.md
    - "Project - Network automation": projects/network-automation/apic-project.md
    - "Project - Cloud automation": projects/cloud-automation/aws-project.md
    - "Project - DCIM automation": projects/dcim-ipam-automation/netbox-project.md
  - "Ansible Advanced":
    - ansible-advanced-overview.md
    - ansible-navigator/ansible-navigator.md

